language: python
python:
  - "3.6"

cache:
  apt: true
  pip: true
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/pyqt

env:
  global:
    - CC_TEST_REPORTER_ID=28eec73378bc43dced99c6442cc796e59b664415537fb07f783fa63b8d25c9b5

before_install:
  - set -e  # fail on any error
  - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
  - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build coverage.py --exit-code $TRAVIS_TEST_RESULT; fi
