language: python
python:
  - "3.6"

cache:
  apt: true
  pip: true
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/pyqt

before_install:
  - set -e  # fail on any error
  - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
  - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

script:
  - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh
