language: python
python:
  - "3.6"

cache:
  apt: true
  pip: true
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/pyqt

before_install:
  - set -e  # fail on any error

install:
  - source $TRAVIS_BUILD_DIR/.travis/install_pyqt.sh
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  - pytest
